package rpc.interfaces;

import rpc.structs.*;

//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!


public interface Autobots{

	public static final int _def_pno = 4;
	public static final int _def_vno = 1;

	public static final int _getMap_proc = 1;

	public mapConfig getMap() throws netbula.ORPC.rpc_err;

	public static final int _getBotPosition_proc = 2;

	public botPosition getBotPosition() throws netbula.ORPC.rpc_err;

	public static final int _getLayout_proc = 3;

	public mapLayoutPercent getLayout() throws netbula.ORPC.rpc_err;


}

