module autobots {
	
	struct boxAndGoalConfig {
		short boxPosX;
		short boxPosY;
		short goalPosX;
		short goalPosY;
	};
	
  interface autobots {

	  boxAndGoalConfig getBoxPosition(in string caminho, in short botPosX, in short botPosY);

  };

};
