package rpc.structs;

//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!



import java.io.Serializable;

import netbula.ORPC.*;

public class botPosition implements XDT, Serializable{
	public int x;
	public int y;

	public XDT Clone() { return new botPosition();}

	public XDT [] getArray(int len) { return new botPosition[len];}

	public void xdr(XDR xdrs) throws XDRError{
		switch(xdrs.xdr_op){
		case XDR.XDR_ENCODE:
		xdrs.enc_int(x);
		xdrs.enc_int(y);
		break;

		case XDR.XDR_DECODE:
		x = xdrs.dec_int();
		y = xdrs.dec_int();
		break;

		}
	}
};
