package rpc.structs;

//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!



import java.io.Serializable;

import netbula.ORPC.*;

public class mapConfig implements XDT, Serializable{
	public String caminho;
	public int linhas;
	public int colunas;

	public XDT Clone() { return new mapConfig();}

	public XDT [] getArray(int len) { return new mapConfig[len];}

	public void xdr(XDR xdrs) throws XDRError{
		switch(xdrs.xdr_op){
		case XDR.XDR_ENCODE:
		xdrs.enc_String(caminho);
		xdrs.enc_int(linhas);
		xdrs.enc_int(colunas);
		break;

		case XDR.XDR_DECODE:
		caminho = xdrs.dec_String();
		linhas = xdrs.dec_int();
		colunas = xdrs.dec_int();
		break;

		}
	}
};
