package rpc.structs;

//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!



import java.io.Serializable;

import netbula.ORPC.*;

public class mapLayoutPercent implements XDT, Serializable{
	public int waterPercent;
	public int grassPercent;
	public int treesPercent;

	public XDT Clone() { return new mapLayoutPercent();}

	public XDT [] getArray(int len) { return new mapLayoutPercent[len];}

	public void xdr(XDR xdrs) throws XDRError{
		switch(xdrs.xdr_op){
		case XDR.XDR_ENCODE:
		xdrs.enc_int(waterPercent);
		xdrs.enc_int(grassPercent);
		xdrs.enc_int(treesPercent);
		break;

		case XDR.XDR_DECODE:
		waterPercent = xdrs.dec_int();
		grassPercent = xdrs.dec_int();
		treesPercent = xdrs.dec_int();
		break;

		}
	}
};
