package server;

//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!



import netbula.ORPC.*;
import rpc.interfaces.*;
import rpc.structs.*;

abstract public class Autobots_svcb extends Svc implements Autobots {

	public Autobots_svcb(int prog, int ver) {
		super(prog, ver);
	}

	public Autobots_svcb() {
		super(Autobots._def_pno, Autobots._def_vno);
	}

	abstract public mapConfig getMap() ;

	abstract public botPosition getBotPosition() ;

	abstract public mapLayoutPercent getLayout() ;

	public XDT proc_call (int proc, XDR inXDR) throws XDRError {
		switch(proc) {
		case 0: return new XDTvoid();

		case 1:
		mapConfig _out_arg1;
		_out_arg1 = this.getMap();
		return _out_arg1;

		case 2:
		botPosition _out_arg2;
		_out_arg2 = this.getBotPosition();
		return _out_arg2;

		case 3:
		mapLayoutPercent _out_arg3;
		_out_arg3 = this.getLayout();
		return _out_arg3;

		default: return null;
		}
	}

}

