package corba.structs.autobots;


/**
* autobots/_autobotsStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.structs.autobots.idl
* Quarta-feira, 18 de Novembro de 2009 00h18min47s BRST
*/

public class _autobotsStub extends org.omg.CORBA.portable.ObjectImpl implements corba.structs.autobots.autobots
{

  public corba.structs.autobots.boxAndGoalConfig getBoxPosition (String map, short botPosX, short botPosY)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getBoxPosition", true);
                $out.write_string (map);
                $out.write_short (botPosX);
                $out.write_short (botPosY);
                $in = _invoke ($out);
                corba.structs.autobots.boxAndGoalConfig $result = corba.structs.autobots.boxAndGoalConfigHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getBoxPosition (map, botPosX, botPosY        );
            } finally {
                _releaseReply ($in);
            }
  } // getBoxPosition

  public void getPathToBox (String serverhost, short botPosX, short botPosY, short boxPosX, short boxPosY, org.omg.CORBA.StringHolder ret)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPathToBox", true);
                $out.write_string (serverhost);
                $out.write_short (botPosX);
                $out.write_short (botPosY);
                $out.write_short (boxPosX);
                $out.write_short (boxPosY);
                $in = _invoke ($out);
                ret.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getPathToBox (serverhost, botPosX, botPosY, boxPosX, boxPosY, ret        );
            } finally {
                _releaseReply ($in);
            }
  } // getPathToBox

  public void getPathToTarget (String serverhost, short botPosX, short botPosY, short targetPosX, short targetPosY, org.omg.CORBA.StringHolder ret)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPathToTarget", true);
                $out.write_string (serverhost);
                $out.write_short (botPosX);
                $out.write_short (botPosY);
                $out.write_short (targetPosX);
                $out.write_short (targetPosY);
                $in = _invoke ($out);
                ret.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getPathToTarget (serverhost, botPosX, botPosY, targetPosX, targetPosY, ret        );
            } finally {
                _releaseReply ($in);
            }
  } // getPathToTarget

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:autobots/autobots:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _autobotsStub
