package corba.structs.autobots;


/**
* autobots/_autobotsStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Autobots.idl
* Segunda-feira, 16 de Novembro de 2009 19h49min14s BRST
*/

public class _autobotsStub extends org.omg.CORBA.portable.ObjectImpl implements corba.structs.autobots.autobots
{

  public boolean getBoxPosition (String caminho, short botPosX, short botPosY, org.omg.CORBA.ShortHolder boxPosX, org.omg.CORBA.ShortHolder boxPosY)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getBoxPosition", true);
                $out.write_string (caminho);
                $out.write_short (botPosX);
                $out.write_short (botPosY);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                boxPosX.value = $in.read_short ();
                boxPosY.value = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getBoxPosition (caminho, botPosX, botPosY, boxPosX, boxPosY        );
            } finally {
                _releaseReply ($in);
            }
  } // getBoxPosition

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:autobots/autobots:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _autobotsStub
