package corba.structs.autobots;


/**
* autobots/autobots.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Autobots.idl
* Segunda-feira, 16 de Novembro de 2009 19h49min14s BRST
*/

public interface autobots extends autobotsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface autobots
