package corba.structs.autobots;


/**
* autobots/autobotsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Autobots.idl
* Segunda-feira, 16 de Novembro de 2009 19h49min14s BRST
*/

public abstract class autobotsPOA extends org.omg.PortableServer.Servant
 implements corba.structs.autobots.autobotsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getBoxPosition", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // autobots/autobots/getBoxPosition
       {
         String caminho = in.read_string ();
         short botPosX = in.read_short ();
         short botPosY = in.read_short ();
         org.omg.CORBA.ShortHolder boxPosX = new org.omg.CORBA.ShortHolder ();
         org.omg.CORBA.ShortHolder boxPosY = new org.omg.CORBA.ShortHolder ();
         boolean $result = false;
         $result = this.getBoxPosition (caminho, botPosX, botPosY, boxPosX, boxPosY);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_short (boxPosX.value);
         out.write_short (boxPosY.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:autobots/autobots:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public autobots _this() 
  {
    return autobotsHelper.narrow(
    super._this_object());
  }

  public autobots _this(org.omg.CORBA.ORB orb) 
  {
    return autobotsHelper.narrow(
    super._this_object(orb));
  }


} // class autobotsPOA
