package corba.structs.autobots;


/**
* autobots/autobotsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Autobots.idl
* Segunda-feira, 16 de Novembro de 2009 19h49min14s BRST
*/

public interface autobotsOperations 
{
  boolean getBoxPosition (String caminho, short botPosX, short botPosY, org.omg.CORBA.ShortHolder boxPosX, org.omg.CORBA.ShortHolder boxPosY);
} // interface autobotsOperations
