package corba.structs.autobots;


/**
* autobots/autobots.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Autobots.idl
* Quarta-feira, 18 de Novembro de 2009 22h57min19s GMT-03:00
*/

public interface autobots extends autobotsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface autobots
