package corba.structs.autobots;

/**
* autobots/boxAndGoalConfigHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.structs.autobots.idl
* Quarta-feira, 18 de Novembro de 2009 00h18min47s BRST
*/

public final class boxAndGoalConfigHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.structs.autobots.boxAndGoalConfig value = null;

  public boxAndGoalConfigHolder ()
  {
  }

  public boxAndGoalConfigHolder (corba.structs.autobots.boxAndGoalConfig initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.structs.autobots.boxAndGoalConfigHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.structs.autobots.boxAndGoalConfigHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.structs.autobots.boxAndGoalConfigHelper.type ();
  }

}
