package corba.structs.autobots;


/**
* autobots/boxAndGoalConfig.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.structs.autobots.idl
* Quinta-feira, 19 de Novembro de 2009 00h09min50s BRST
*/

public final class boxAndGoalConfig implements org.omg.CORBA.portable.IDLEntity
{
  public short boxPosX = (short)0;
  public short boxPosY = (short)0;
  public short goalPosX = (short)0;
  public short goalPosY = (short)0;

  public boxAndGoalConfig ()
  {
  } // ctor

  public boxAndGoalConfig (short _boxPosX, short _boxPosY, short _goalPosX, short _goalPosY)
  {
    boxPosX = _boxPosX;
    boxPosY = _boxPosY;
    goalPosX = _goalPosX;
    goalPosY = _goalPosY;
  } // ctor

} // class boxAndGoalConfig
