package corba.structs.autobots;


/**
* autobots/boxAndGoalConfigHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.structs.autobots.idl
* Quinta-feira, 19 de Novembro de 2009 00h09min50s BRST
*/

abstract public class boxAndGoalConfigHelper
{
  private static String  _id = "IDL:autobots/boxAndGoalConfig/boxAndGoalConfig:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.structs.autobots.boxAndGoalConfig that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.structs.autobots.boxAndGoalConfig extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[0] = new org.omg.CORBA.StructMember (
            "boxPosX",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[1] = new org.omg.CORBA.StructMember (
            "boxPosY",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[2] = new org.omg.CORBA.StructMember (
            "goalPosX",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[3] = new org.omg.CORBA.StructMember (
            "goalPosY",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (corba.structs.autobots.boxAndGoalConfigHelper.id (), "boxAndGoalConfig", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.structs.autobots.boxAndGoalConfig read (org.omg.CORBA.portable.InputStream istream)
  {
    corba.structs.autobots.boxAndGoalConfig value = new corba.structs.autobots.boxAndGoalConfig ();
    value.boxPosX = istream.read_short ();
    value.boxPosY = istream.read_short ();
    value.goalPosX = istream.read_short ();
    value.goalPosY = istream.read_short ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.structs.autobots.boxAndGoalConfig value)
  {
    ostream.write_short (value.boxPosX);
    ostream.write_short (value.boxPosY);
    ostream.write_short (value.goalPosX);
    ostream.write_short (value.goalPosY);
  }

}
